const FETCH_CURRENCY_PENDING = 'FETCH_CURRENCY_PENDING';
const FETCH_CURRENCY_SUCCESS = 'FETCH_CURRENCY_SUCCESS';
const FETCH_CURRENCY_ERROR = 'FETCH_CURRENCY_ERROR';

export { FETCH_CURRENCY_PENDING, FETCH_CURRENCY_SUCCESS, FETCH_CURRENCY_ERROR };
